/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../Services/FileParser.service';
import * as i2 from './FileDropZone';
import * as i3 from '../Services/FileStore.service';
const styles_FileDropZone:any[] = ['\n        .file_dropZone_internal {\n            border: 3px dashed #DDD;\n            border-radius:10px;\n            padding:10px;\n            width:400px;\n            height:200px;\n            color:#CCC;\n            text-align:center;\n            display:table-cell;\n            vertical-align:middle;\n            cursor:pointer;\n        }\n    '];
export const RenderType_FileDropZone:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_FileDropZone,
    data:{}});
export function View_FileDropZone_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n        '])),i0.ɵncd((null as any),
      0),(_l()(),i0.ɵted((null as any),['\n    ']))],(null as any),(null as any));
}
export function View_FileDropZone_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'fileDropZone',
      ([] as any[]),(null as any),[[(null as any),'drop'],[(null as any),'dragenter'],
          [(null as any),'dragover'],[(null as any),'dragleave'],[(null as any),'click']],
      (_v,en,$event) => {
        var ad:boolean = true;
        if (('drop' === en)) {
          const pd_0:any = ((<any>i0.ɵnov(_v,2).drop($event)) !== false);
          ad = (pd_0 && ad);
        }
        if (('dragenter' === en)) {
          const pd_1:any = ((<any>i0.ɵnov(_v,2).dragenter($event)) !== false);
          ad = (pd_1 && ad);
        }
        if (('dragover' === en)) {
          const pd_2:any = ((<any>i0.ɵnov(_v,2).dragover($event)) !== false);
          ad = (pd_2 && ad);
        }
        if (('dragleave' === en)) {
          const pd_3:any = ((<any>i0.ɵnov(_v,2).dragleave($event)) !== false);
          ad = (pd_3 && ad);
        }
        if (('click' === en)) {
          const pd_4:any = ((<any>i0.ɵnov(_v,2).onClick($event)) !== false);
          ad = (pd_4 && ad);
        }
        return ad;
      },View_FileDropZone_0,RenderType_FileDropZone)),i0.ɵprd(512,(null as any),i1.FileParser,
      i1.FileParser,([] as any[])),i0.ɵdid(49152,(null as any),0,i2.FileDropZone,[i3.FilesStore,
      i0.ElementRef,i1.FileParser],(null as any),(null as any))],(null as any),(null as any));
}
export const FileDropZoneNgFactory:i0.ComponentFactory<i2.FileDropZone> = i0.ɵccf('fileDropZone, [fileDropZone]',
    i2.FileDropZone,View_FileDropZone_Host_0,{},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3B0a2FjaC9Eb2N1bWVudHMvd29yay9wcm9qZWN0cy90ZXN0L2FwcmlsMjAxNy9zcmMvRGlyZWN0aXZlcy9GaWxlRHJvcFpvbmUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvcHRrYWNoL0RvY3VtZW50cy93b3JrL3Byb2plY3RzL3Rlc3QvYXByaWwyMDE3L3NyYy9EaXJlY3RpdmVzL0ZpbGVEcm9wWm9uZS50cyIsIm5nOi8vL1VzZXJzL3B0a2FjaC9Eb2N1bWVudHMvd29yay9wcm9qZWN0cy90ZXN0L2FwcmlsMjAxNy9zcmMvRGlyZWN0aXZlcy9GaWxlRHJvcFpvbmUudHMuRmlsZURyb3Bab25lLmh0bWwiLCJuZzovLy9Vc2Vycy9wdGthY2gvRG9jdW1lbnRzL3dvcmsvcHJvamVjdHMvdGVzdC9hcHJpbDIwMTcvc3JjL0RpcmVjdGl2ZXMvRmlsZURyb3Bab25lLnRzLkZpbGVEcm9wWm9uZV9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICA8bmctY29udGVudD48L25nLWNvbnRlbnQ+XG4gICAgIiwiPGZpbGVEcm9wWm9uZT48L2ZpbGVEcm9wWm9uZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLHNEQUNRO01BQUEsR0FBeUI7OztvQkNEakM7TUFBQTtVQUFBO01BQUE7UUFBQTtRQUFBO1VBQUE7VUFBQTtRQUFBO1FBQUE7VUFBQTtVQUFBO1FBQUE7UUFBQTtVQUFBO1VBQUE7UUFBQTtRQUFBO1VBQUE7VUFBQTtRQUFBO1FBQUE7VUFBQTtVQUFBO1FBQUE7UUFBQTtNQUFBO29CQUFBLHNCQUFBO2lDQUFBOzs7In0=
