/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './File.ngfactory';
import * as i2 from './File';
import * as i3 from '@angular/common';
import * as i4 from './FileList';
import * as i5 from '../Services/FileStore.service';
const styles_FileList:any[] = ['.file-list[_ngcontent-%COMP%] {\n            width: 430px;\n            margin-bottom: 5px;\n            display: flex;\n            flex-flow: wrap;\n            justify-content: flex-start;\n         }'];
export const RenderType_FileList:i0.RendererType2 = i0.ɵcrt({encapsulation:0,styles:styles_FileList,
    data:{}});
function View_FileList_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'fileItem',([] as any[]),
      (null as any),[[(null as any),'removeFile']],(_v,en,$event) => {
        var ad:boolean = true;
        var _co:any = _v.component;
        if (('removeFile' === en)) {
          const pd_0:any = ((<any>_co.removeFile(_v.context.$implicit)) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },i1.View_File_0,i1.RenderType_File)),i0.ɵdid(1097728,(null as any),0,i2.File,
      ([] as any[]),{file:[0,'file'],percentage:[1,'percentage'],loadingSuccessful:[2,
          'loadingSuccessful'],responseMessage:[3,'responseMessage']},{removeFile:'removeFile'}),
      (_l()(),i0.ɵted((null as any),['\n            ']))],(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit.File;
    const currVal_1:any = _v.context.$implicit.percentage;
    const currVal_2:any = _v.context.$implicit.loadingSuccessful;
    const currVal_3:any = _v.context.$implicit.responseMessage;
    _ck(_v,1,0,currVal_0,currVal_1,currVal_2,currVal_3);
  },(null as any));
}
export function View_FileList_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),4,'div',[['class','file-list']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['\n            '])),
      (_l()(),i0.ɵand(16777216,(null as any),(null as any),1,(null as any),View_FileList_1)),
      i0.ɵdid(802816,(null as any),0,i3.NgForOf,[i0.ViewContainerRef,i0.TemplateRef,
          i0.IterableDiffers],{ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n        '])),(_l()(),i0.ɵted((null as any),['\n    ']))],(_ck,_v) => {
    var _co:i4.FileList = _v.component;
    const currVal_0:any = _co.filesStore.iFiles;
    _ck(_v,4,0,currVal_0);
  },(null as any));
}
export function View_FileList_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'fileList',([] as any[]),
      (null as any),(null as any),(null as any),View_FileList_0,RenderType_FileList)),
      i0.ɵdid(49152,(null as any),0,i4.FileList,[i5.FilesStore],(null as any),(null as any))],
      (null as any),(null as any));
}
export const FileListNgFactory:i0.ComponentFactory<i4.FileList> = i0.ɵccf('fileList, [fileList]',
    i4.FileList,View_FileList_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3B0a2FjaC9Eb2N1bWVudHMvd29yay9wcm9qZWN0cy90ZXN0L2FwcmlsMjAxNy9zcmMvRGlyZWN0aXZlcy9GaWxlTGlzdC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9wdGthY2gvRG9jdW1lbnRzL3dvcmsvcHJvamVjdHMvdGVzdC9hcHJpbDIwMTcvc3JjL0RpcmVjdGl2ZXMvRmlsZUxpc3QudHMiLCJuZzovLy9Vc2Vycy9wdGthY2gvRG9jdW1lbnRzL3dvcmsvcHJvamVjdHMvdGVzdC9hcHJpbDIwMTcvc3JjL0RpcmVjdGl2ZXMvRmlsZUxpc3QudHMuRmlsZUxpc3QuaHRtbCIsIm5nOi8vL1VzZXJzL3B0a2FjaC9Eb2N1bWVudHMvd29yay9wcm9qZWN0cy90ZXN0L2FwcmlsMjAxNy9zcmMvRGlyZWN0aXZlcy9GaWxlTGlzdC50cy5GaWxlTGlzdF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICA8ZGl2IGNsYXNzPVwiZmlsZS1saXN0XCI+XG4gICAgICAgICAgICA8ZmlsZUl0ZW0gKm5nRm9yPVwibGV0IGZpbGUgb2YgZmlsZXNTdG9yZS5pRmlsZXNcIlxuICAgICAgICAgICAgICAgIFtmaWxlXT1cImZpbGUuRmlsZVwiXG4gICAgICAgICAgICAgICAgW3BlcmNlbnRhZ2VdPVwiZmlsZS5wZXJjZW50YWdlXCJcbiAgICAgICAgICAgICAgICBbbG9hZGluZ1N1Y2Nlc3NmdWxdPVwiZmlsZS5sb2FkaW5nU3VjY2Vzc2Z1bFwiXG4gICAgICAgICAgICAgICAgW3Jlc3BvbnNlTWVzc2FnZV09XCJmaWxlLnJlc3BvbnNlTWVzc2FnZVwiXG4gICAgICAgICAgICAgICAgKHJlbW92ZUZpbGUpPVwicmVtb3ZlRmlsZShmaWxlKVwiPlxuICAgICAgICAgICAgPC9maWxlSXRlbT5cbiAgICAgICAgPC9kaXY+XG4gICAgIiwiPGZpbGVMaXN0PjwvZmlsZUxpc3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0VZO01BQUE7UUFBQTtRQUFBO1FBS0k7VUFBQTtVQUFBO1FBQUE7UUFMSjtNQUFBLDZDQUFBO01BQUE7VUFBQTtNQUtvQztJQUpoQztJQUNBO0lBQ0E7SUFDQTtJQUpKLFdBQ0ksVUFDQSxVQUNBLFVBQ0EsU0FKSjs7OztvQkFGWiwrQ0FDUTtNQUFBO01BQUEsNENBQXVCO01BQ25CO2FBQUE7NEJBQUEseUNBTVc7VUFBQSxpQkFDVDs7SUFQUTtJQUFWLFdBQVUsU0FBVjs7OztvQkNGWjtNQUFBO2FBQUE7Ozs7In0=
